# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'MeTag' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MeTag
  pod 'shared', :path => '../shared'

  # Firebase for push notifications
  pod 'FirebaseCore', '~> 11.0'
  pod 'FirebaseMessaging', '~> 11.0'
end
