// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANzycZS1fGb4D2rrvs0K9Axe7XwBEfdTI',
    appId: '1:28419194559:android:0498c4a31406f02c31500a',
    messagingSenderId: '28419194559',
    projectId: 'metag-69e35',
    databaseURL: 'https://metag-69e35.firebaseio.com',
    storageBucket: 'metag-69e35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsl8kWJUefprDZ0KlFAlrSNM62IkqaciI',
    appId: '1:28419194559:ios:780b6541f6df90bb31500a',
    messagingSenderId: '28419194559',
    projectId: 'metag-69e35',
    databaseURL: 'https://metag-69e35.firebaseio.com',
    storageBucket: 'metag-69e35.firebasestorage.app',
    iosClientId: '28419194559-pa3iq50u96frtjqkdhepteb2v825deu1.apps.googleusercontent.com',
    iosBundleId: 'uni.bremen.metag',
  );
}
